# Generated by Django 5.1.3 on 2024-12-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10, null=True)),
                ('address', models.TextField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('FEMALE', 'FEMALE')], max_length=10)),
            ],
        ),
    ]
